# Permalinks
permalink:        none

# Setup
url:              http://myanbin.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            '饮冰先生'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  关于代码和一切

# The tags listed as entries in the sidebar
sidebar_tags:     []

# Google Analytics tracking ID
ga_id:            'UA-35742418-1'

# Fallback image and color if not overwritten for tag or post
image:            /public/img/shinkansen.jpg
color:            '#A85641'

author:
  name:           '饮冰先生'
  github:         myanbin
  linkedin:       myanbin
  weibo:          yianbin
  photo:          http://ww4.sinaimg.cn/mw690/b22ba716jw1f2n4w5haf9j20ci0ciq4f.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是饮冰先生，热爱前端与黑客文化，喜欢与人交流分享。我的微博 [@孺子牛骑士](http://weibo.com/yianbin)
